gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /captcha

r3gis_app:
    resource: "@R3gisAppBundle/Controller/"
    type:     annotation
    prefix:   /

r3gis_api:
    resource: "@R3gisAppBundle/Controller/Api"
    type:     annotation
    prefix:   /api/1/
